# DigitalOcean Deployment for NFL Pickem
# Cost: $12/month (Basic Droplet) + $15/month (Database) = $27/month

version: '3.8'

services:
  nfl-pickem:
    image: openjdk:17-jdk-slim
    container_name: nfl-pickem-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=digitalocean
      - THEODDS_API_KEY=${THEODDS_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./target:/app
    working_dir: /app
    command: java -jar pickem-0.0.1-SNAPSHOT.jar
    restart: unless-stopped
    networks:
      - nfl-pickem-network

  nginx:
    image: nginx:alpine
    container_name: nfl-pickem-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nfl-pickem
    restart: unless-stopped
    networks:
      - nfl-pickem-network

networks:
  nfl-pickem-network:
    driver: bridge
