[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/pickem-0.0.1-SNAPSHOT.jar"
