services:
  - type: web
    name: nfl-pickem
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/pickem-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: render
    healthCheckPath: /actuator/health
    autoDeploy: true
